services:
  backend:
    # build:
    #   context: ./backend
    image: simonangelfong/gitops-demo:backend
    environment:
      APP_VERSION: ${APP_VERSION:-1.4.1}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

  frontend:
    # build:
    #   context: ./frontend
    image: simonangelfong/gitops-demo:frontend
    environment:
      BACKEND_URL: http://backend:8080
      NGINX_ENVSUBST_FILTER: BACKEND_URL
    ports:
      - "8000:8080"
    depends_on:
      backend:
        condition: service_healthy
